#index:
#    path: /
#    controller: App\Controller\DefaultController::index
student_create:
  path: api/student
  controller: App\Controller\StudentController:addStudent
  methods: [POST]
api_login_check:
  path: api/login_check

Register:
  path: /register
  controller: App\Controller\AuthController:Register
  methods: [POST]